rufzeichen: „OE0BOT“
dmr_id: 123456
hb_server_ip: „127.0.0.1“
hb_server_port: 62031
master_password: „changeme“
talkgroup_rx: 9
talkgroup_tx: 9
timeslot_rx: 2
timeslot_tx: 2
language: „de“
tts_engine: „espeak“ # oder „piper“
phonetic_callsign: true
operator_name: „Sebastian“
qth_city: „Graz“
qth_country: „Austria“
locator: „JN76pp“
rig_model: „TYT MD-UV390“
openai_api_key: „your_openai_api_key_here“
