rufzeichen: "OE0BOT"
dmr_id: "1234567"
hb_server_ip: "127.0.0.1"
hb_server_port: 62031
master_password: "changeme"
talkgroup_rx: 7
talkgroup_tx: 7
timeslot_rx: 2
timeslot_tx: 2
language: "de"
tts_engine: "espeak"
phonetic_callsign: true
announce_on_first_contact: true
operator_name: "Sebastian"
qth_city: "Graz"
qth_country: "Austria"
locator: "JN76pp"
rig_model: "TYT MD-UV390"
